FROM base-dev:latest

RUN sudo pacman --noconfirm -Syuu && \
    sudo pacman --noconfirm --verbose -S gcc ninja cmake make xmake gdb perf && \
    sudo rm -rf /var/cache/pacman/pkg/* /usr/share/man/* /usr/share/locale/* /var/log/* /tmp/*
