FROM gcc-dev:latest

RUN sudo pacman --noconfirm -Syu && \
    sudo pacman --noconfirm --verbose -S base-devel clang llvm libbpf bpf elfutils linux-headers && \
    sudo rm -rf /var/cache/pacman/pkg/* /usr/share/man/* /usr/share/locale/* /var/log/* /tmp/*
